# Proyecto Integrador de Aprendizaje Automático

Para las empresas financieras se sabe que poder predecir el riesgo de incumplimiento en préstamos es importante para minimizar pérdidas y ayudas en decisiones de la vida crediticia del sujeto. Por ello, nos vamos a enfoca en construir un modelo de clasificación en el que podamos interpretar los préstamos que serán pagados en su totalidad o parcial, cuánto quedarán debiendo y/o aquellos que estarían en default.

In [8]:
import pandas as pd

archivo_entrada = "data_proyect.csv"
archivo_salida = "data_proyect_limpio.csv"

# Definir tamaño de los chunks (ajústalo según memoria disponible)
chunksize = 10_000  

# Abrimos archivo de salida en modo escritura y guardamos encabezado
with open(archivo_salida, "w", encoding="utf-8") as f_out:
    for i, chunk in enumerate(pd.read_csv(archivo_entrada, sep=",", chunksize=chunksize, low_memory=False)):
        # Procesamos cada bloque (ejemplo: eliminar filas vacías)
        chunk = chunk.dropna(how="all")

        if i == 0:
            # Primera vez: escribimos con encabezados
            chunk.to_csv(f_out, index=False)
        else:
            # Resto: escribimos sin encabezados
            chunk.to_csv(f_out, index=False, header=False)

In [1]:
import pandas as pd

archivo_salida = "data_proyect_limpio.csv"

df = pd.read_csv(archivo_salida)

C:\Users\Administrador\AppData\Local\Temp\ipykernel_30524\353150501.py:5: DtypeWarning: Columns (0,19,49,59,118,129,130,131,134,135,136,139,145,146,147) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(archivo_salida)

In [2]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2260701 entries, 0 to 2260700
Columns: 151 entries, id to settlement_term
dtypes: float64(113), object(38)
memory usage: 2.5+ GB

In [3]:
df.head()

,id,member_id,loan_amnt,funded_amnt,funded_amnt_inv,term,int_rate,installment,grade,sub_grade,...,hardship_payoff_balance_amount,hardship_last_payment_amount,disbursement_method,debt_settlement_flag,debt_settlement_flag_date,settlement_status,settlement_date,settlement_amount,settlement_percentage,settlement_term
0,68407277,NaN,3600.0,3600.0,3600.0,36 months,13.99,123.03,C,C4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
1,68355089,NaN,24700.0,24700.0,24700.0,36 months,11.99,820.28,C,C1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
2,68341763,NaN,20000.0,20000.0,20000.0,60 months,10.78,432.66,B,B4,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
3,66310712,NaN,35000.0,35000.0,35000.0,60 months,14.85,829.90,C,C5,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN
4,68476807,NaN,10400.0,10400.0,10400.0,60 months,22.45,289.91,F,F1,...,NaN,NaN,Cash,N,NaN,NaN,NaN,NaN,NaN,NaN

In [4]:
print("Dimensiones:", df.shape)

Dimensiones: (2260701, 151)

In [6]:
summary = pd.DataFrame({
    'Tipo': df.dtypes,
    'Nulos': df.isnull().sum(),
    'No nulos': df.notnull().sum(),
    'Únicos': df.nunique()
})

pd.set_option('display.max_rows', 200)
display(summary)

,Tipo,Nulos,No nulos,Únicos
id,object,0,2260701,2260701
member_id,float64,2260701,0,0
loan_amnt,float64,33,2260668,1572
funded_amnt,float64,33,2260668,1572
funded_amnt_inv,float64,33,2260668,10057
term,object,33,2260668,2
int_rate,float64,33,2260668,673
installment,float64,33,2260668,93301
grade,object,33,2260668,7
sub_grade,object,33,2260668,35
emp_title,object,167002,2093699,512694
emp_length,object,146940,2113761,11
home_ownership,object,33,2260668,6
annual_inc,float64,37,2260664,89368
verification_status,object,33,2260668,3
issue_d,object,33,2260668,139
loan_status,object,33,2260668,9
pymnt_plan,object,33,2260668,2
url,object,33,2260668,2260668
desc,object,2134636,126065,124500
purpose,object,33,2260668,14
title,object,23359,2237342,63154
zip_code,object,34,2260667,956
addr_state,object,33,2260668,51
dti,float64,1744,2258957,10845
delinq_2yrs,float64,62,2260639,37
earliest_cr_line,object,62,2260639,754
fico_range_low,float64,33,2260668,48
fico_range_high,float64,33,2260668,48
inq_last_6mths,float64,63,2260638,28
mths_since_last_delinq,float64,1158535,1102166,173
mths_since_last_record,float64,1901545,359156,129
open_acc,float64,62,2260639,91
pub_rec,float64,62,2260639,43
revol_bal,float64,33,2260668,102251
revol_util,float64,1835,2258866,1430
total_acc,float64,62,2260639,152
initial_list_status,object,33,2260668,2
out_prncp,float64,33,2260668,356141
out_prncp_inv,float64,33,2260668,368481
total_pymnt,float64,33,2260668,1633855
total_pymnt_inv,float64,33,2260668,1311099
total_rec_prncp,float64,33,2260668,486463
total_rec_int,float64,33,2260668,635921
total_rec_late_fee,float64,33,2260668,18375
recoveries,float64,33,2260668,132777
collection_recovery_fee,float64,33,2260668,146222
last_pymnt_d,object,2460,2258241,136
last_pymnt_amnt,float64,33,2260668,704467
next_pymnt_d,object,1345343,915358,106
last_credit_pull_d,object,105,2260596,141
last_fico_range_high,float64,33,2260668,72
last_fico_range_low,float64,33,2260668,71
collections_12_mths_ex_med,float64,178,2260523,16
mths_since_last_major_derog,float64,1679926,580775,183
policy_code,float64,33,2260668,1
application_type,object,33,2260668,2
annual_inc_joint,float64,2139991,120710,17633
dti_joint,float64,2139995,120706,4018
verification_status_joint,object,2144971,115730,3
acc_now_delinq,float64,62,2260639,9
tot_coll_amt,float64,70309,2190392,15574
tot_cur_bal,float64,70309,2190392,487688
open_acc_6m,float64,866163,1394538,19
open_act_il,float64,866162,1394539,54
open_il_12m,float64,866162,1394539,19
open_il_24m,float64,866162,1394539,31
mths_since_rcnt_il,float64,909957,1350744,405
total_bal_il,float64,866162,1394539,162249
il_util,float64,1068883,1191818,280
open_rv_12m,float64,866162,1394539,29
open_rv_24m,float64,866162,1394539,50
max_bal_bc,float64,866162,1394539,33726
all_util,float64,866381,1394320,188
total_rev_hi_lim,float64,70309,2190392,34220
inq_fi,float64,866162,1394539,33
total_cu_tl,float64,866163,1394538,62
inq_last_12m,float64,866163,1394538,48
acc_open_past_24mths,float64,50063,2210638,57
avg_cur_bal,float64,70379,2190322,88597
bc_open_to_buy,float64,74968,2185733,91500
bc_util,float64,76104,2184597,1494
chargeoff_within_12_mths,float64,178,2260523,11
delinq_amnt,float64,62,2260639,2617
mo_sin_old_il_acct,float64,139104,2121597,566
mo_sin_old_rev_tl_op,float64,70310,2190391,787
mo_sin_rcnt_rev_tl_op,float64,70310,2190391,333
mo_sin_rcnt_tl,float64,70309,2190392,232
mort_acc,float64,50063,2210638,47
mths_since_recent_bc,float64,73445,2187256,546
mths_since_recent_bc_dlq,float64,1741000,519701,177
mths_since_recent_inq,float64,295468,1965233,26
mths_since_recent_revol_delinq,float64,1520342,740359,179
num_accts_ever_120_pd,float64,70309,2190392,44
num_actv_bc_tl,float64,70309,2190392,42
num_actv_rev_tl,float64,70309,2190392,57
num_bc_sats,float64,58623,2202078,60
num_bc_tl,float64,70309,2190392,76
num_il_tl,float64,70309,2190392,122
num_op_rev_tl,float64,70309,2190392,81
num_rev_accts,float64,70310,2190391,117
num_rev_tl_bal_gt_0,float64,70309,2190392,50
num_sats,float64,58623,2202078,91
num_tl_120dpd_2m,float64,153690,2107011,7
num_tl_30dpd,float64,70309,2190392,5
num_tl_90g_dpd_24m,float64,70309,2190392,34
num_tl_op_past_12m,float64,70309,2190392,33
pct_tl_nvr_dlq,float64,70464,2190237,690
percent_bc_gt_75,float64,75412,2185289,284
pub_rec_bankruptcies,float64,1398,2259303,12
tax_liens,float64,138,2260563,42
tot_hi_cred_lim,float64,70309,2190392,529972
total_bal_ex_mort,float64,50063,2210638,212777
total_bc_limit,float64,50063,2210638,20309
total_il_high_credit_limit,float64,70309,2190392,194137
revol_bal_joint,float64,2152681,108020,56875
sec_app_fico_range_low,float64,2152680,108021,62
sec_app_fico_range_high,float64,2152680,108021,62
sec_app_earliest_cr_line,object,2152680,108021,663
sec_app_inq_last_6mths,float64,2152680,108021,7
sec_app_mort_acc,float64,2152680,108021,23
sec_app_open_acc,float64,2152680,108021,67
sec_app_revol_util,float64,2154517,106184,1216
sec_app_open_act_il,float64,2152680,108021,40
sec_app_num_rev_accts,float64,2152680,108021,86
sec_app_chargeoff_within_12_mths,float64,2152680,108021,22
sec_app_collections_12_mths_ex_med,float64,2152680,108021,18
sec_app_mths_since_last_major_derog,float64,2224759,35942,140
hardship_flag,object,33,2260668,2
hardship_type,object,2249784,10917,1
hardship_reason,object,2249784,10917,9
hardship_status,object,2249784,10917,3
deferral_term,float64,2249784,10917,1
hardship_amount,float64,2249784,10917,9162
hardship_start_date,object,2249784,10917,27
hardship_end_date,object,2249784,10917,28
payment_plan_start_date,object,2249784,10917,27
hardship_length,float64,2249784,10917,1
hardship_dpd,float64,2249784,10917,34
hardship_loan_status,object,2249784,10917,5
orig_projected_additional_accrued_interest,float64,2252050,8651,7487
hardship_payoff_balance_amount,float64,2249784,10917,10893
hardship_last_payment_amount,float64,2249784,10917,9045
disbursement_method,object,33,2260668,2
debt_settlement_flag,object,33,2260668,2
debt_settlement_flag_date,object,2226455,34246,83
settlement_status,object,2226455,34246,3
settlement_date,object,2226455,34246,90
settlement_amount,float64,2226455,34246,21941
settlement_percentage,float64,2226455,34246,2070
settlement_term,float64,2226455,34246,40